package net.runelite.client.plugins.microbot.qualityoflife.enums;

import lombok.Getter;
import java.util.Arrays;
import net.runelite.api.gameval.ItemID;

@Getter
public enum WeaponID {
    // --- Magic Weapons ---
    THIRD_AGE_WAND("3rd age wand", "Magic", new int[]{ItemID.TRAIL_MAGE_WAND}),
    ACCURSED_SCEPTRE("Accursed sceptre", "Magic", new int[]{ItemID.WILD_CAVE_ACCURSED_CHARGED}),
    ACCURSED_SCEPTRE_A("Accursed sceptre (a)", "Magic", new int[]{ItemID.WILD_CAVE_ACCURSED_CHARGED_RECOL}),
    AHRIMS_STAFF("Ahrim's staff", "Magic", new int[]{ItemID.BARROWS_AHRIM_WEAPON}),
    AHRIMS_STAFF_BR("Ahrim's staff BR", "Melee", new int[]{ItemID.BR_BARROWS_AHRIM_WEAPON}),
    AIR_BATTLESTAFF("Air battlestaff", "Magic", new int[]{ItemID.AIR_BATTLESTAFF}),
    AIR_STAFF_BR("Air staff BR", "Magic", new int[]{ItemID.BR_AIR_STAFF}),
    ANCIENT_CROZIER("Ancient crozier", "Magic", new int[]{ItemID.TRAIL_ANCIENT_STAFF}),
    ANCIENT_SCEPTRE("Ancient sceptre", "Magic", new int[]{ItemID.ANCIENT_SCEPTRE}),
    ANCIENT_STAFF("Ancient staff", "Magic", new int[]{ItemID.STAFF_OF_ZAROS}),
    ANCIENT_STAFF_BR("Ancient staff BR", "Melee", new int[]{ItemID.BR_ANCIENT_STAFF}),
    APPRENTICE_WAND("Apprentice wand", "Magic", new int[]{ItemID.MAGICTRAINING_WAND_APPR}),
    APPRENTICE_WAND_BR("Apprentice wand BR", "Magic", new int[]{ItemID.BR_APPRENTICE_WAND}),
    ARMADYL_CROZIER("Armadyl crozier", "Magic", new int[]{ItemID.TRAIL_ARMADYL_STAFF}),
    BANDOS_CROZIER("Bandos crozier", "Magic", new int[]{ItemID.TRAIL_BANDOS_STAFF}),
    BATTLESTAFF("Battlestaff", "Magic", new int[]{ItemID.BATTLESTAFF}),
    BEGINNER_WAND("Beginner wand", "Magic", new int[]{ItemID.MAGICTRAINING_WAND_BEG}),
    BEGINNER_WAND_BR("Beginner wand BR", "Magic", new int[]{ItemID.BR_BEGINNER_WAND}),
    BLACK_SALAMANDER("Black salamander", "Magic", new int[]{ItemID.BLACK_SALAMANDER}),
    BLISTERWOOD_FLAIL("Blisterwood flail", "Magic", new int[]{ItemID.BLISTERWOOD_FLAIL}),
    BLOOD_ANCIENT_SCEPTRE("Blood ancient sceptre", "Magic", new int[]{ItemID.ANCIENT_SCEPTRE_BLOOD}),
    BLUE_MOON_SPEAR("Blue moon spear", "Magic", new int[]{ItemID.FROSTMOON_SPEAR}),
    BLUE_MOON_SPEAR_BR("Blue moon spear BR", "Magic", new int[]{ItemID.BR_FROSTMOON_SPEAR}),
    BONE_STAFF("Bone staff", "Magic", new int[]{ItemID.RAT_BONE_STAFF}),
    BRYOPHYTAS_STAFF("Bryophyta's staff", "Magic", new int[]{ItemID.NATURE_STAFF_CHARGED}),
    DRAGON_HUNTER_WAND("Dragon hunter wand", "Magic", new int[]{ItemID.DRAGONHUNTER_WAND}),
    DRAMEN_STAFF("Dramen staff", "Magic", new int[]{ItemID.DRAMEN_STAFF}),
    DUST_BATTLESTAFF("Dust battlestaff", "Magic", new int[]{ItemID.DUST_BATTLESTAFF}),
    EARTH_BATTLESTAFF("Earth battlestaff", "Magic", new int[]{ItemID.EARTH_BATTLESTAFF}),
    ECHO_AHRIMS_STAFF("Echo ahrim's staff", "Magic", new int[]{ItemID.BARROWS_AHRIM_WEAPON_ORNAMENT}),
    FIRE_BATTLESTAFF("Fire battlestaff", "Magic", new int[]{ItemID.FIRE_BATTLESTAFF}),
    GUTHIX_CROZIER("Guthix crozier", "Magic", new int[]{ItemID.TRAIL_GUTHIX_STAFF}),
    GUTHIX_STAFF("Guthix staff", "Magic", new int[]{ItemID.GUTHIX_STAFF}),
    HOLY_SANGUINESTI_STAFF("Holy sanguinesti staff", "Magic", new int[]{ItemID.SANGUINESTI_STAFF_OR}),
    IBANS_STAFF("Iban's staff", "Magic", new int[]{ItemID.IBANSTAFF}),
    ICE_ANCIENT_SCEPTRE("Ice ancient sceptre", "Magic", new int[]{ItemID.ANCIENT_SCEPTRE_ICE}),
    IVANDIS_FLAIL("Ivandis flail", "Magic", new int[]{ItemID.IVANDIS_FLAIL}),
    KODAI_WAND("Kodai wand", "Magic", new int[]{ItemID.KODAI_WAND}),
    LAVA_BATTLESTAFF("Lava battlestaff", "Magic", new int[]{ItemID.LAVA_BATTLESTAFF}),
    LAVA_BATTLESTAFF_OR("Lava battlestaff (or)", "Magic", new int[]{ItemID.LAVA_BATTLESTAFF_PRETTY}),
    MAGIC_STAFF("Magic staff", "Magic", new int[]{ItemID.MAGIC_STAFF}),
    MASTER_WAND("Master wand", "Magic", new int[]{ItemID.MAGICTRAINING_WAND_MASTER}),
    MASTER_WAND_BR("Master wand BR", "Magic", new int[]{ItemID.BR_MASTER_WAND}),
    MIST_BATTLESTAFF("Mist battlestaff", "Magic", new int[]{ItemID.MIST_BATTLESTAFF}),
    MUD_BATTLESTAFF("Mud battlestaff", "Magic", new int[]{ItemID.MUD_BATTLESTAFF}),
    MYSTIC_AIR_STAFF("Mystic air staff", "Magic", new int[]{ItemID.MYSTIC_AIR_STAFF}),
    MYSTIC_DUST_STAFF("Mystic dust staff", "Magic", new int[]{ItemID.MYSTIC_DUST_BATTLESTAFF}),
    MYSTIC_EARTH_STAFF("Mystic earth staff", "Magic", new int[]{ItemID.MYSTIC_EARTH_STAFF}),
    MYSTIC_FIRE_STAFF("Mystic fire staff", "Magic", new int[]{ItemID.MYSTIC_FIRE_STAFF}),
    MYSTIC_LAVA_STAFF("Mystic lava staff", "Magic", new int[]{ItemID.MYSTIC_LAVA_STAFF}),
    MYSTIC_LAVA_STAFF_OR("Mystic lava staff (or)", "Magic", new int[]{ItemID.MYSTIC_LAVA_STAFF_PRETTY}),
    MYSTIC_MIST_STAFF("Mystic mist staff", "Magic", new int[]{ItemID.MYSTIC_MIST_BATTLESTAFF}),
    MYSTIC_MUD_STAFF("Mystic mud staff", "Magic", new int[]{ItemID.MYSTIC_MUD_STAFF}),
    MYSTIC_SMOKE_STAFF("Mystic smoke staff", "Magic", new int[]{ItemID.MYSTIC_SMOKE_BATTLESTAFF}),
    MYSTIC_STEAM_STAFF("Mystic steam staff", "Magic", new int[]{ItemID.MYSTIC_STEAM_BATTLESTAFF}),
    MYSTIC_STEAM_STAFF_OR("Mystic steam staff (or)", "Magic", new int[]{}),
    MYSTIC_WATER_STAFF("Mystic water staff", "Magic", new int[]{ItemID.MYSTIC_WATER_STAFF}),
    NIGHTMARE_STAFF("Nightmare staff", "Magic", new int[]{ItemID.NIGHTMARE_STAFF}),
    ORANGE_SALAMANDER("Orange salamander", "Magic", new int[]{ItemID.ORANGE_SALAMANDER}),
    PHARAOHS_SCEPTRE("Pharaoh's sceptre", "Magic", new int[]{ItemID.PHARAOHS_SCEPTRE}),
    PURGING_STAFF("Purging staff", "Magic", new int[]{ItemID.PURGING_STAFF}),
    RED_SALAMANDER("Red salamander", "Magic", new int[]{ItemID.RED_SALAMANDER}),
    SANGUINESTI_STAFF("Sanguinesti staff", "Magic", new int[]{ItemID.SANGUINESTI_STAFF}),
    SARADOMIN_CROZIER("Saradomin crozier", "Magic", new int[]{ItemID.TRAIL_SARADOMIN_STAFF}),
    SARADOMIN_STAFF("Saradomin staff", "Magic", new int[]{ItemID.SARADOMIN_STAFF}),
    SHADOW_ANCIENT_SCEPTRE("Shadow ancient sceptre", "Magic", new int[]{ItemID.ANCIENT_SCEPTRE_SHADOW}),
    SKULL_SCEPTRE("Skull sceptre", "Magic", new int[]{ItemID.SOS_SKULL_SCEPTRE}),
    SKULL_SCEPTRE_I("Skull sceptre (i)", "Magic", new int[]{ItemID.SOS_SKULL_SCEPTRE_IMBUED}),
    SLAYERS_STAFF("Slayer's staff", "Magic", new int[]{ItemID.SLAYER_STAFF}),
    SLAYERS_STAFF_E("Slayer's staff (e)", "Magic", new int[]{ItemID.SLAYER_STAFF_ENCHANTED}),
    SMOKE_ANCIENT_SCEPTRE("Smoke ancient sceptre", "Magic", new int[]{ItemID.ANCIENT_SCEPTRE_SMOKE}),
    SMOKE_BATTLESTAFF("Smoke battlestaff", "Magic", new int[]{ItemID.SMOKE_BATTLESTAFF}),
    SOULFLAME_HORN("Soulflame horn", "Magic", new int[]{ItemID.SOULFLAME_HORN}),
    STAFF_OF_AIR("Staff of air", "Magic", new int[]{ItemID.STAFF_OF_AIR}),
    STAFF_OF_BALANCE("Staff of balance", "Magic", new int[]{ItemID.STAFF_OF_BALANCE}),
    STAFF_OF_BOB_THE_CAT("Staff of bob the cat", "Magic", new int[]{ItemID.STAFF_OF_BOBCAT}),
    STAFF_OF_EARTH("Staff of earth", "Magic", new int[]{ItemID.STAFF_OF_EARTH}),
    STAFF_OF_FIRE("Staff of fire", "Magic", new int[]{ItemID.STAFF_OF_FIRE}),
    STAFF_OF_LIGHT("Staff of light", "Magic", new int[]{ItemID.STAFF_OF_LIGHT}),
    STAFF_OF_THE_DEAD("Staff of the dead", "Magic", new int[]{ItemID.SOTD}),
    STAFF_OF_THE_DEAD_BR("Staff of the dead BR", "Melee", new int[]{ItemID.BR_SOTD}),
    STAFF_OF_WATER("Staff of water", "Magic", new int[]{ItemID.STAFF_OF_WATER}),
    STEAM_BATTLESTAFF("Steam battlestaff", "Magic", new int[]{ItemID.STEAM_BATTLESTAFF}),
    STEAM_BATTLESTAFF_OR("Steam battlestaff (or)", "Magic", new int[]{}),
    TEACHER_WAND("Teacher wand", "Magic", new int[]{ItemID.MAGICTRAINING_WAND_TEACH}),
    THAMMARONS_SCEPTRE("Thammaron's sceptre", "Magic", new int[]{}),
    THAMMARONS_SCEPTRE_A("Thammaron's sceptre (a)", "Magic", new int[]{}),
    TOKTZ_MEJ_TAL("Toktz-mej-tal", "Magic", new int[]{ItemID.TZHAAR_STAFF}),
    TOXIC_STAFF_OF_THE_DEAD("Toxic staff of the dead", "Magic", new int[]{ItemID.SOTD}),
    TRIDENT_OF_THE_SEAS("Trident of the seas", "Magic", new int[]{ItemID.TOTS_CHARGED}),
    TRIDENT_OF_THE_SEAS_E("Trident of the seas (e)", "Magic", new int[]{ItemID.TOTS_I_CHARGED}),
    TRIDENT_OF_THE_SWAMP("Trident of the swamp", "Magic", new int[]{ItemID.TOXIC_TOTS_CHARGED}),
    TRIDENT_OF_THE_SWAMP_E("Trident of the swamp (e)", "Magic", new int[]{ItemID.TOXIC_TOTS_I_CHARGED}),
    TUMEKENS_SHADOW("Tumeken's shadow", "Magic", new int[]{ItemID.TUMEKENS_SHADOW}),
    CORRUPTED_TUMEKENS_SHADOW("Corrupted tumeken's shadow", "Magic", new int[]{ItemID.DEADMAN_BLIGHTED_TUMEKENS_SHADOW}),
    TWINFLAME_STAFF("Twinflame staff", "Magic", new int[]{ItemID.TWINFLAME_STAFF}),
    WARPED_SCEPTRE("Warped sceptre", "Magic", new int[]{ItemID.WARPED_SCEPTRE}),
    WATER_BATTLESTAFF("Water battlestaff", "Magic", new int[]{ItemID.WATER_BATTLESTAFF}),
    WHITE_MAGIC_STAFF("White magic staff", "Magic", new int[]{ItemID.WHITE_MAGIC_STAFF}),
    ZAMORAK_CROZIER("Zamorak crozier", "Magic", new int[]{ItemID.TRAIL_ZAMORAK_STAFF}),
    ZAMORAK_STAFF("Zamorak staff", "Magic", new int[]{ItemID.ZAMORAK_STAFF}),
    ZURIELS_STAFF_BH("Zuriel's staff (bh)", "Magic", new int[]{ItemID.ZURIELS_STAFF_BH}),
    ZURIELS_STAFF_DEADMAN_MODE("Zuriel's staff (Deadman Mode)", "Magic", new int[]{ItemID.BR_ZURIELS_STAFF}),

    // --- Ranged Weapons ---
    THIRD_AGE_BOW("3rd age bow", "Ranged", new int[]{ItemID.TRAIL_RANGER_BOW}),
    ADAMANT_CROSSBOW("Adamant crossbow", "Ranged", new int[]{ItemID.XBOWS_CROSSBOW_ADAMANTITE}),
    ADAMANT_DART("Adamant dart", "Ranged", new int[]{ItemID.ADAMANT_DART}),
    ADAMANT_KNIFE("Adamant knife", "Ranged", new int[]{ItemID.ADAMANT_KNIFE}),
    ADAMANT_SCIMITAR_BR("Adamant scimitar BR", "Melee", new int[]{ItemID.BR_ADAMANT_SCIMITAR}),
    ADAMANT_THROWNAXE("Adamant thrownaxe", "Ranged", new int[]{ItemID.ADAMNT_THROWNAXE}),
    AMETHYST_DART("Amethyst dart", "Ranged", new int[]{ItemID.AMETHYST_DART}),
    ARMADYL_CROSSBOW("Armadyl crossbow", "Ranged", new int[]{ItemID.ACB}),
    ARMADYL_CROSSBOW_BR("Armadyl crossbow BR", "Ranged", new int[]{ItemID.BR_ACB}),
    BLACK_CHINCHOMPA("Black chinchompa", "Ranged", new int[]{ItemID.CHINCHOMPA_BLACK}),
    BLACK_DART("Black dart", "Ranged", new int[]{ItemID.BLACK_DART}),
    BLACK_KNIFE("Black knife", "Ranged", new int[]{ItemID.BLACK_KNIFE}),
    BLURITE_CROSSBOW("Blurite crossbow", "Ranged", new int[]{ItemID.XBOWS_CROSSBOW_BLURITE}),
    BONE_SHORTBOW("Bone shortbow", "Ranged", new int[]{}),
    BOW_OF_FAERDHINEN("Bow of faerdhinen", "Ranged", new int[]{ItemID.BOW_OF_FAERDHINEN}),
    BOW_OF_FAERDHINEN_C("Bow of faerdhinen C", "Ranged", new int[]{ItemID.BOW_OF_FAERDHINEN_INFINITE}),
    BRONZE_CROSSBOW("Bronze crossbow", "Ranged", new int[]{ItemID.XBOWS_CROSSBOW_BRONZE}),
    BRONZE_DART("Bronze dart", "Ranged", new int[]{ItemID.BRONZE_DART}),
    BRONZE_KNIFE("Bronze knife", "Ranged", new int[]{ItemID.BRONZE_KNIFE}),
    BRONZE_THROWNAXE("Bronze thrownaxe", "Ranged", new int[]{ItemID.BRONZE_THROWNAXE}),
    CRAWS_BOW("Craw's bow", "Ranged", new int[]{}),
    CRYSTAL_BOW("Crystal bow", "Ranged", new int[]{ItemID.CRYSTAL_BOW}),
    CRYSTAL_BOW_I("Crystal bow (i)", "Ranged", new int[]{ItemID.CRYSTAL_BOW_2500}),
    CURSED_GOBLIN_BOW("Cursed goblin bow", "Ranged", new int[]{}),
    DARK_BOW("Dark bow", "Ranged", new int[]{ItemID.DARKBOW}),
    DARK_BOW_BH("Dark bow (bh)", "Ranged", new int[]{ItemID.BR_DARKBOW}),
    DARK_BOW_BH_CR("Dark bow BH CR", "Ranged", new int[]{ItemID.BH_DARKBOW_IMBUE}),
    DARK_BOW_DM("Dark bow DM", "Ranged", new int[]{ItemID.DEADMAN_DARKBOW}),
    DARK_BOW_CR_DM("Dark bow CR DM", "Ranged", new int[]{ItemID.DEADMAN_BLIGHTED_DARK_BOW}),
    DORGESHUUN_CROSSBOW("Dorgeshuun crossbow", "Ranged", new int[]{}),
    DRAGON_CROSSBOW("Dragon crossbow", "Ranged", new int[]{ItemID.XBOWS_CROSSBOW_DRAGON}),
    DRAGON_DART("Dragon dart", "Ranged", new int[]{ItemID.DRAGON_DART}),
    DRAGON_DAGGER_BR("Dragon dagger BR", "Ranged", new int[]{ItemID.BR_DRAGON_DAGGER}),
    DRAGON_HUNTER_CROSSBOW("Dragon hunter crossbow", "Ranged", new int[]{ItemID.DRAGONHUNTER_XBOW}),
    DRAGON_HUNTER_CROSSBOW_B("Dragon hunter crossbow (b)", "Ranged", new int[]{}),
    DRAGON_HUNTER_CROSSBOW_T("Dragon hunter crossbow (t)", "Ranged", new int[]{}),
    DRAGON_KNIFE("Dragon knife", "Ranged", new int[]{ItemID.DRAGON_KNIFE}),
    DRAGON_KNIFE_BR("Dragon knife BR", "Ranged", new int[]{ItemID.BR_DRAGON_KNIFE}),
    DRAGON_THROWNAXE("Dragon thrownaxe", "Ranged", new int[]{ItemID.DRAGON_THROWNAXE}),
    ECHO_VENATOR_BOW("Echo venator bow", "Ranged", new int[]{}),
    ECLIPSE_ATLATL("Eclipse atlatl", "Ranged", new int[]{}),
    ECLIPSE_ATLATL_BR("Eclipse atlatl BR", "Ranged", new int[]{ItemID.BR_ECLIPSE_ATLATL}),
    HEAVY_BALLISTA("Heavy ballista", "Ranged", new int[]{}),
    HUNTERS_SPEAR("Hunter's spear", "Ranged", new int[]{}),
    HUNTERS_CROSSBOW("Hunters' crossbow", "Ranged", new int[]{}),
    HUNTERS_SUNLIGHT_CROSSBOW("Hunters' sunlight crossbow", "Ranged", new int[]{}),
    IRON_CROSSBOW("Iron crossbow", "Ranged", new int[]{ItemID.XBOWS_CROSSBOW_IRON}),
    IRON_DART("Iron dart", "Ranged", new int[]{ItemID.IRON_DART}),
    IRON_KNIFE("Iron knife", "Ranged", new int[]{ItemID.IRON_KNIFE}),
    IRON_THROWNAXE("Iron thrownaxe", "Ranged", new int[]{ItemID.IRON_THROWNAXE}),
    KARILS_CROSSBOW("Karil's crossbow", "Ranged", new int[]{}),
    LIGHT_BALLISTA("Light ballista", "Ranged", new int[]{}),
    LIGHT_RANGED_WEAPONS("Light Ranged weapons", "Ranged", new int[]{}),
    LONGBOW("Longbow", "Ranged", new int[]{ItemID.LONGBOW}),
    LONGBOW_WEAPON("Longbow (weapon)", "Ranged", new int[]{}),
    MAGIC_COMP_BOW("Magic comp bow", "Ranged", new int[]{}),
    MAGIC_LONGBOW("Magic longbow", "Ranged", new int[]{ItemID.MAGIC_LONGBOW}),
    MAGIC_SHORTBOW("Magic shortbow", "Ranged", new int[]{ItemID.MAGIC_SHORTBOW}),
    MAGIC_SHORTBOW_BR("Magic shortbow BR", "Ranged", new int[]{ItemID.BR_MAGIC_BOW}),
    MAGIC_SHORTBOW_I("Magic shortbow (i)", "Ranged", new int[]{ItemID.MAGIC_SHORTBOW_I}),
    MAPLE_LONGBOW("Maple longbow", "Ranged", new int[]{ItemID.MAPLE_LONGBOW}),
    MAPLE_SHORTBOW("Maple shortbow", "Ranged", new int[]{ItemID.MAPLE_SHORTBOW}),
    MAPLE_SHORTBOW_BR("Maple shortbow BR", "Ranged", new int[]{ItemID.BR_MAPLE_BOW}),
    MITHRIL_CROSSBOW("Mithril crossbow", "Ranged", new int[]{ItemID.XBOWS_CROSSBOW_MITHRIL}),
    MITHRIL_DART("Mithril dart", "Ranged", new int[]{ItemID.MITHRIL_DART}),
    MITHRIL_KNIFE("Mithril knife", "Ranged", new int[]{ItemID.MITHRIL_KNIFE}),
    MITHRIL_SCIMITAR_BR("Mithril scimitar BR", "Melee", new int[]{ItemID.BR_MITHRIL_SCIMITAR}),
    MITHRIL_THROWNAXE("Mithril thrownaxe", "Ranged", new int[]{ItemID.MITHRIL_THROWNAXE}),
    MORRIGANS_THROWING_AXE_BH("Morrigan's throwing axe (bh)", "Ranged", new int[]{ItemID.MORRIGANS_THROWNAXE_BH}),
    OAK_LONGBOW("Oak longbow", "Ranged", new int[]{ItemID.OAK_LONGBOW}),
    OAK_SHORTBOW("Oak shortbow", "Ranged", new int[]{ItemID.OAK_SHORTBOW}),
    PHOENIX_CROSSBOW("Phoenix crossbow", "Ranged", new int[]{ItemID.PHOENIX_CROSSBOW}),
    RAIN_BOW("Rain bow", "Ranged", new int[]{}),
    RED_CHINCHOMPA("Red chinchompa", "Ranged", new int[]{}),
    RUNE_CROSSBOW("Rune crossbow", "Ranged", new int[]{ItemID.XBOWS_CROSSBOW_RUNITE}),
    RUNE_CROSSBOW_BR("Rune crossbow BR", "Ranged", new int[]{ItemID.BR_XBOWS_CROSSBOW_RUNITE}),
    RUNE_CROSSBOW_OR("Rune crossbow (or)", "Ranged", new int[]{ItemID.LEAGUE_3_RUNE_XBOW}),
    RUNE_DART("Rune dart", "Ranged", new int[]{ItemID.RUNE_DART}),
    RUNE_KNIFE("Rune knife", "Ranged", new int[]{ItemID.RUNE_KNIFE}),
    RUNE_THROWNAXE("Rune thrownaxe", "Ranged", new int[]{ItemID.RUNE_THROWNAXE}),
    SCORCHING_BOW("Scorching bow", "Ranged", new int[]{}),
    SEERCULL("Seercull", "Ranged", new int[]{}),
    SHORTBOW("Shortbow", "Ranged", new int[]{ItemID.SHORTBOW}),
    SIGNED_OAK_BOW("Signed oak bow", "Ranged", new int[]{}),
    STANDARD_RANGED_WEAPONS("Standard Ranged weapons", "Ranged", new int[]{}),
    STEEL_CROSSBOW("Steel crossbow", "Ranged", new int[]{ItemID.XBOWS_CROSSBOW_STEEL}),
    STEEL_DART("Steel dart", "Ranged", new int[]{ItemID.STEEL_DART}),
    STEEL_KNIFE("Steel knife", "Ranged", new int[]{ItemID.STEEL_KNIFE}),
    STEEL_THROWNAXE("Steel thrownaxe", "Ranged", new int[]{ItemID.STEEL_THROWNAXE}),
    THROWING_AXE("Throwing axe", "Ranged", new int[]{}),
    THROWING_KNIFE("Throwing knife", "Ranged", new int[]{}),
    TOKTZ_XIL_UL("Toktz-xil-ul", "Ranged", new int[]{}),
    TONALZTICS_OF_RALOS("Tonalztics of ralos", "Ranged", new int[]{}),
    TOXIC_BLOWPIPE("Toxic blowpipe", "Ranged", new int[]{ItemID.TOXIC_BLOWPIPE_LOADED}),
    TWISTED_BOW("Twisted bow", "Ranged", new int[]{ItemID.TWISTED_BOW}),
    TWISTED_BOW_CORRUPTED_DM("Twisted bow corrupted DM", "Ranged", new int[]{ItemID.DEADMAN_BLIGHTED_TWISTED_BOW}),
    VENATOR_BOW("Venator bow", "Ranged", new int[]{}),
    WEBWEAVER_BOW("Webweaver bow", "Ranged", new int[]{}),
    WILLOW_COMP_BOW("Willow comp bow", "Ranged", new int[]{}),
    WILLOW_LONGBOW("Willow longbow", "Ranged", new int[]{ItemID.WILLOW_LONGBOW}),
    WILLOW_SHORTBOW("Willow shortbow", "Ranged", new int[]{ItemID.WILLOW_SHORTBOW}),
    WILLOW_SHORTBOW_BR("Willow shortbow BR", "Ranged", new int[]{ItemID.BR_WILLOW_BOW}),
    YEW_COMP_BOW("Yew comp bow", "Ranged", new int[]{}),
    YEW_LONGBOW("Yew longbow", "Ranged", new int[]{ItemID.YEW_LONGBOW}),
    YEW_SHORTBOW("Yew shortbow", "Ranged", new int[]{ItemID.YEW_SHORTBOW}),
    YEW_SHORTBOW_BR("Yew shortbow BR", "Ranged", new int[]{ItemID.BR_YEW_BOW}),
    ZARYTE_CROSSBOW("Zaryte crossbow", "Ranged", new int[]{}),

    // --- Melee Weapons ---
    THIRD_AGE_LONGSWORD("3rd age longsword", "Melee", new int[]{}),
    ABYSSAL_BLUDGEON("Abyssal bludgeon", "Melee", new int[]{ItemID.ABYSSAL_BLUDGEON}),
    ABYSSAL_DAGGER("Abyssal dagger", "Melee", new int[]{ItemID.ABYSSAL_DAGGER}),
    ABYSSAL_DAGGER_BH("Abyssal dagger (bh)", "Melee", new int[]{ItemID.BH_ABYSSAL_DAGGER_IMBUE}),
    ABYSSAL_DAGGER_BH_P("Abyssal dagger (bh)(p)", "Melee", new int[]{ItemID.BH_ABYSSAL_DAGGER_P_IMBUE}),
    ABYSSAL_DAGGER_BH_PP("Abyssal dagger (bh)(p+)", "Melee", new int[]{ItemID.BH_ABYSSAL_DAGGER_P__IMBUE}),
    ABYSSAL_DAGGER_BH_PPP("Abyssal dagger (bh)(p++)", "Melee", new int[]{ItemID.BH_ABYSSAL_DAGGER_P___IMBUE}),
    ABYSSAL_TENTACLE("Abyssal tentacle", "Melee", new int[]{ItemID.ABYSSAL_TENTACLE}),
    ABYSSAL_TENTACLE_OR("Abyssal tentacle (or)", "Melee", new int[]{ItemID.LEAGUE_3_WHIP_TENTACLE}),
    ABYSSAL_WHIP("Abyssal whip", "Melee", new int[]{ItemID.ABYSSAL_WHIP}),
    ABYSSAL_WHIP_BR("Abyssal whip BR", "Melee", new int[]{ItemID.BR_ABYSSAL_WHIP}),
    ABYSSAL_WHIP_OR("Abyssal whip (or)", "Melee", new int[]{ItemID.LEAGUE_3_WHIP}),
    ABYSSAL_WHIP_V("Abyssal whip V", "Melee", new int[]{ItemID.ABYSSAL_WHIP_LAVA}),
    ABYSSAL_WHIP_F("Abyssal whip F", "Melee", new int[]{ItemID.ABYSSAL_WHIP_ICE}),
    ADAMANT_2H_SWORD("Adamant 2h sword", "Melee", new int[]{ItemID.ADAMANT_2H_SWORD}),
    ADAMANT_BATTLEAXE("Adamant battleaxe", "Melee", new int[]{ItemID.ADAMANT_BATTLEAXE}),
    ADAMANT_CLAWS("Adamant claws", "Melee", new int[]{}),
    ADAMANT_DAGGER("Adamant dagger", "Melee", new int[]{ItemID.ADAMANT_DAGGER}),
    ADAMANT_HALBERD("Adamant halberd", "Melee", new int[]{}),
    ADAMANT_HASTA("Adamant hasta", "Melee", new int[]{}),
    ADAMANT_LONGSWORD("Adamant longsword", "Melee", new int[]{ItemID.ADAMANT_LONGSWORD}),
    ADAMANT_MACE("Adamant mace", "Melee", new int[]{ItemID.ADAMANT_MACE}),
    ADAMANT_SCIMITAR("Adamant scimitar", "Melee", new int[]{ItemID.ADAMANT_SCIMITAR}),
    ADAMANT_SPEAR("Adamant spear", "Melee", new int[]{}),
    ADAMANT_SWORD("Adamant sword", "Melee", new int[]{ItemID.ADAMANT_SWORD}),
    ADAMANT_WARHAMMER("Adamant warhammer", "Melee", new int[]{}),
    ANCIENT_GODSWORD("Ancient godsword", "Melee", new int[]{ItemID.ANCIENT_GODSWORD}),
    ANCIENT_MACE("Ancient mace", "Melee", new int[]{}),
    ARCLIGHT("Arclight", "Melee", new int[]{}),
    ARMADYL_GODSWORD("Armadyl godsword", "Melee", new int[]{}),
    ARMADYL_GODSWORD_OR("Armadyl godsword (or)", "Melee", new int[]{}),
    ARMADYL_GODSWORD_CORRUPTED_DM("Armadyl godsword corrupted DM", "Melee", new int[]{ItemID.DEADMAN_BLIGHTED_AGS}),
    BANDOS_GODSWORD("Bandos godsword", "Melee", new int[]{}),
    BANDOS_GODSWORD_OR("Bandos godsword (or)", "Melee", new int[]{}),
    BANNER("Banner", "Melee", new int[]{}),
    BARRELCHEST_ANCHOR("Barrelchest anchor", "Melee", new int[]{}),
    BARRELCHEST_ANCHOR_BH("Barrelchest anchor (bh)", "Melee", new int[]{}),
    BARRONITE_MACE("Barronite mace", "Melee", new int[]{ItemID.BARRONITE_MACE}),
    BATTLEAXE("Battleaxe", "Melee", new int[]{}),
    BLACK_2H_SWORD("Black 2h sword", "Melee", new int[]{ItemID.BLACK_2H_SWORD}),
    BLACK_BATTLEAXE("Black battleaxe", "Melee", new int[]{ItemID.BLACK_BATTLEAXE}),
    BLACK_CLAWS("Black claws", "Melee", new int[]{}),
    BLACK_DAGGER("Black dagger", "Melee", new int[]{ItemID.BLACK_DAGGER}),
    BLACK_HALBERD("Black halberd", "Melee", new int[]{}),
    BLACK_LONGSWORD("Black longsword", "Melee", new int[]{ItemID.BLACK_LONGSWORD}),
    BLACK_MACE("Black mace", "Melee", new int[]{ItemID.BLACK_MACE}),
    BLACK_SCIMITAR("Black scimitar", "Melee", new int[]{ItemID.BLACK_SCIMITAR}),
    BLACK_SPEAR("Black spear", "Melee", new int[]{}),
    BLACK_SWORD("Black sword", "Melee", new int[]{ItemID.BLACK_SWORD}),
    BLACK_WARHAMMER("Black warhammer", "Melee", new int[]{}),
    BLADE_OF_SAELDOR("Blade of saeldor", "Melee", new int[]{ItemID.BLADE_OF_SAELDOR}),
    BLADE_OF_SAELDOR_C("Blade of saeldor (c)", "Melee", new int[]{ItemID.BLADE_OF_SAELDOR_INFINITE}),
    BLURITE_SWORD("Blurite sword", "Melee", new int[]{}),
    BONE_CLUB("Bone club", "Melee", new int[]{}),
    BONE_DAGGER("Bone dagger", "Melee", new int[]{}),
    BONE_MACE("Bone mace", "Melee", new int[]{}),
    BONE_SPEAR("Bone spear", "Melee", new int[]{}),
    BRINE_SABRE("Brine sabre", "Melee", new int[]{}),
    BRONZE_2H_SWORD("Bronze 2h sword", "Melee", new int[]{ItemID.BRONZE_2H_SWORD}),
    BRONZE_BATTLEAXE("Bronze battleaxe", "Melee", new int[]{ItemID.BRONZE_BATTLEAXE}),
    BRONZE_CLAWS("Bronze claws", "Melee", new int[]{}),
    BRONZE_DAGGER("Bronze dagger", "Melee", new int[]{ItemID.BRONZE_DAGGER}),
    BRONZE_HALBERD("Bronze halberd", "Melee", new int[]{}),
    BRONZE_HASTA("Bronze hasta", "Melee", new int[]{}),
    BRONZE_LONGSWORD("Bronze longsword", "Melee", new int[]{ItemID.BRONZE_LONGSWORD}),
    BRONZE_MACE("Bronze mace", "Melee", new int[]{ItemID.BRONZE_MACE}),
    BRONZE_SCIMITAR("Bronze scimitar", "Melee", new int[]{ItemID.BRONZE_SCIMITAR}),
    BRONZE_SPEAR("Bronze spear", "Melee", new int[]{}),
    BRONZE_SWORD("Bronze sword", "Melee", new int[]{ItemID.BRONZE_SWORD}),
    BRONZE_WARHAMMER("Bronze warhammer", "Melee", new int[]{}),
    CRYSTAL_HALBERD("Crystal halberd", "Melee", new int[]{}),
    CRYSTAL_HALBERD_I("Crystal halberd (i)", "Melee", new int[]{}),
    CUTLASS("Cutlass", "Melee", new int[]{}),
    DARK_DAGGER("Dark dagger", "Melee", new int[]{}),
    DARKLIGHT("Darklight", "Melee", new int[]{}),
    DAWNBRINGER("Dawnbringer", "Melee", new int[]{}),
    DHAROKS_GREATAXE("Dharok's greataxe", "Melee", new int[]{ItemID.BARROWS_DHAROK_WEAPON}),
    DHAROKS_GREATAXE_BR("Dharok's greataxe BR", "Melee", new int[]{ItemID.BR_BARROWS_DHAROK_WEAPON}),
    DRAGON_2H_SWORD("Dragon 2h sword", "Melee", new int[]{ItemID.DRAGON_2H_SWORD}),
    DRAGON_2H_SWORD_CR("Dragon 2h sword (cr)", "Melee", new int[]{ItemID.BH_DRAGON_2H_SWORD_CORRUPTED}),
    DRAGON_BATTLEAXE("Dragon battleaxe", "Melee", new int[]{ItemID.DRAGON_BATTLEAXE}),
    DRAGON_BATTLEAXE_CR("Dragon battleaxe (cr)", "Melee", new int[]{ItemID.BH_DRAGON_BATTLEAXE_CORRUPTED}),
    DRAGON_CLAWS("Dragon claws", "Melee", new int[]{}),
    DRAGON_CLAWS_CR("Dragon claws (cr)", "Melee", new int[]{ItemID.BH_DRAGON_CLAWS_CORRUPTED}),
    DRAGON_CLAWS_CORRUPTED_DM("Dragon claws corrupted DM", "Melee", new int[]{ItemID.DEADMAN_BLIGHTED_DRAGON_CLAWS}),
    DRAGON_DAGGER("Dragon dagger", "Melee", new int[]{ItemID.DRAGON_DAGGER}),
    DRAGON_DAGGER_CR("Dragon dagger (cr)", "Melee", new int[]{ItemID.BH_DRAGON_DAGGER_CORRUPTED}),
    DRAGON_DAGGER_P("Dragon dagger (p)", "Melee", new int[]{ItemID.DRAGON_DAGGER_P}),
    DRAGON_DAGGER_PP("Dragon dagger (p+)", "Melee", new int[]{ItemID.DRAGON_DAGGER_P_}),
    DRAGON_DAGGER_PPP("Dragon dagger (p++)", "Melee", new int[]{ItemID.DRAGON_DAGGER_P__}),
    DRAGON_HALBERD("Dragon halberd", "Melee", new int[]{}),
    DRAGON_HALBERD_CR("Dragon halberd (cr)", "Melee", new int[]{ItemID.BH_DRAGON_HALBERD_CORRUPTED}),
    DRAGON_HASTA("Dragon hasta", "Melee", new int[]{}),
    DRAGON_HUNTER_LANCE("Dragon hunter lance", "Melee", new int[]{}),
    DRAGON_LONGSWORD("Dragon longsword", "Melee", new int[]{ItemID.DRAGON_LONGSWORD}),
    DRAGON_LONGSWORD_BH("Dragon longsword (bh)", "Melee", new int[]{ItemID.BH_DRAGON_LONGSWORD_IMBUE}),
    DRAGON_LONGSWORD_CR_BH("Dragon longsword (cr)", "Melee", new int[]{ItemID.BH_DRAGON_LONGSWORD_CORRUPTED}),
    DRAGON_MACE("Dragon mace", "Melee", new int[]{ItemID.DRAGON_MACE}),
    DRAGON_MACE_BH("Dragon mace (bh)", "Melee", new int[]{ItemID.BH_DRAGON_MACE_IMBUE}),
    DRAGON_MACE_CR_BH("Dragon mace (cr)", "Melee", new int[]{ItemID.BH_DRAGON_MACE_CORRUPTED}),
    DRAGON_SCIMITAR("Dragon scimitar", "Melee", new int[]{ItemID.DRAGON_SCIMITAR}),
    DRAGON_SCIMITAR_CR_BH("Dragon scimitar (cr)", "Melee", new int[]{ItemID.BH_DRAGON_SCIMITAR_CORRUPTED}),
    DRAGON_SCIMITAR_OR("Dragon scimitar (or)", "Melee", new int[]{ItemID.DRAGON_SCIMITAR_ORNAMENT}),
    DRAGON_SCIMITAR_BH("Dragon scimitar BH", "Melee", new int[]{ItemID.BR_DRAGON_SCIMITAR}),
    DRAGON_SPEAR("Dragon spear", "Melee", new int[]{}),
    DRAGON_SPEAR_CR_BH("Dragon spear (cr)", "Melee", new int[]{ItemID.BH_DRAGON_SPEAR_CORRUPTED}),
    DRAGON_SPEAR_P_CR_BH("Dragon spear (p)(cr)", "Melee", new int[]{ItemID.BH_DRAGON_SPEAR_P_CORRUPTED}),
    DRAGON_SPEAR_PP_CR_BH("Dragon spear (p+)(cr)", "Melee", new int[]{ItemID.BH_DRAGON_SPEAR_P__CORRUPTED}),
    DRAGON_SWORD("Dragon sword", "Melee", new int[]{ItemID.DRAGON_SHORTSWORD}),
    DRAGON_SWORD_CR("Dragon sword (cr)", "Melee", new int[]{ItemID.BH_DRAGON_SHORTSWORD_CORRUPTED}),
    DRAGON_SWORD_BR("Dragon sword BR", "Melee", new int[]{ItemID.BR_DRAGON_SWORD}),
    DRAGON_WARHAMMER("Dragon warhammer", "Melee", new int[]{}),
    DRAGON_WARHAMMER_CR("Dragon warhammer (cr)", "Melee", new int[]{ItemID.BH_DRAGON_WARHAMMER_CORRUPTED}),
    DUAL_MACUAHUITL("Dual macuahuitl", "Melee", new int[]{}),
    DUAL_MACUAHUITL_BR("Dual macuahuitl BR", "Melee", new int[]{ItemID.BR_DUAL_MACUAHUITL}),
    DUAL_SAI("Dual sai", "Melee", new int[]{ItemID.DUAL_SAI}),
    ELDER_MAUL("Elder maul", "Melee", new int[]{ItemID.ELDER_MAUL}),
    ELDER_MAUL_OR("Elder maul (or)", "Melee", new int[]{ItemID.ELDER_MAUL_ORNAMENT}),
    ELDER_MAUL_BR("Elder maul BR", "Melee", new int[]{ItemID.BR_ELDER_MAUL}),
    EMBERLIGHT("Emberlight", "Melee", new int[]{}),
    EXCALIBUR("Excalibur", "Melee", new int[]{}),
    FAKE_DRAGON_HASTAKP("Fake dragon hasta(kp)", "Melee", new int[]{}),
    FREMENNIK_BLADE("Fremennik blade", "Melee", new int[]{}),
    FROZEN_ABYSSAL_WHIP("Frozen abyssal whip", "Melee", new int[]{}),
    GADDERHAMMER("Gadderhammer", "Melee", new int[]{}),
    GHRAZI_RAPIER("Ghrazi rapier", "Melee", new int[]{ItemID.GHRAZI_RAPIER}),
    GHRAZI_RAPIER_BR("Ghrazi rapier BR", "Melee", new int[]{ItemID.BR_GHRAZI_RAPIER}),
    HOLY_GHRAZI_RAPIER("Holy ghrazi rapier", "Melee", new int[]{ItemID.GHRAZI_RAPIER_OR}),
    GIANT_BRONZE_DAGGER("Giant bronze dagger", "Melee", new int[]{}),
    GILDED_2H_SWORD("Gilded 2h sword", "Melee", new int[]{}),
    GILDED_HASTA("Gilded hasta", "Melee", new int[]{}),
    GILDED_SCIMITAR("Gilded scimitar", "Melee", new int[]{}),
    GILDED_SPEAR("Gilded spear", "Melee", new int[]{}),
    GLACIAL_TEMOTLI("Glacial temotli", "Melee", new int[]{}),
    GLOWING_DAGGER("Glowing dagger", "Melee", new int[]{}),
    GRANITE_HAMMER("Granite hammer", "Melee", new int[]{}),
    GRANITE_LONGSWORD("Granite longsword", "Melee", new int[]{ItemID.GRANITE_LONGSWORD}),
    GRANITE_MAUL("Granite maul", "Melee", new int[]{ItemID.GRANITE_MAUL}),
    GRANITE_MAUL_I("Granite maul (i)", "Melee", new int[]{ItemID.GRANITE_MAUL_PRETTY}),
    GRANITE_MAUL_BR("Granite maul BR", "Melee", new int[]{ItemID.BR_GRANITE_MAUL}),
    GRANITE_MAUL_PLUS("Granite maul plus", "Melee", new int[]{ItemID.GRANITE_MAUL_PLUS}),
    GRANITE_MAUL_PLUS_I("Granite maul plus (i)", "Melee", new int[]{ItemID.GRANITE_MAUL_PRETTY_PLUS}),
    GUTHANS_WARSPEAR("Guthan's warspear", "Melee", new int[]{}),
    GUTHIX_MJOLNIR("Guthix mjolnir", "Melee", new int[]{}),
    HARRYS_CUTLASS("Harry's cutlass", "Melee", new int[]{}),
    HILL_GIANT_CLUB("Hill giant club", "Melee", new int[]{}),
    HOLY_SCYTHE_OF_VITUR("Holy scythe of vitur", "Melee", new int[]{}),
    INQUISITORS_MACE("Inquisitor's mace", "Melee", new int[]{ItemID.INQUISITORS_MACE}),
    INQUISITORS_MACE_BR("Inquisitor's mace BR", "Melee", new int[]{ItemID.BR_INQUISITORS_MACE}),
    IRON_2H_SWORD("Iron 2h sword", "Melee", new int[]{ItemID.IRON_2H_SWORD}),
    IRON_BATTLEAXE("Iron battleaxe", "Melee", new int[]{ItemID.IRON_BATTLEAXE}),
    IRON_CLAWS("Iron claws", "Melee", new int[]{}),
    IRON_DAGGER("Iron dagger", "Melee", new int[]{ItemID.IRON_DAGGER}),
    IRON_HALBERD("Iron halberd", "Melee", new int[]{}),
    IRON_HASTA("Iron hasta", "Melee", new int[]{}),
    IRON_LONGSWORD("Iron longsword", "Melee", new int[]{ItemID.IRON_LONGSWORD}),
    IRON_MACE("Iron mace", "Melee", new int[]{ItemID.IRON_MACE}),
    IRON_SCIMITAR("Iron scimitar", "Melee", new int[]{ItemID.IRON_SCIMITAR}),
    IRON_SICKLE("Iron sickle", "Melee", new int[]{}),
    IRON_SPEAR("Iron spear", "Melee", new int[]{}),
    IRON_SWORD("Iron sword", "Melee", new int[]{ItemID.IRON_SWORD}),
    IRON_WARHAMMER("Iron warhammer", "Melee", new int[]{}),
    KERIS_PARTISAN("Keris partisan", "Melee", new int[]{}),
    KERIS_PARTISAN_OF_BREACHING("Keris partisan of breaching", "Melee", new int[]{}),
    KERIS_PARTISAN_OF_CORRUPTION("Keris partisan of corruption", "Melee", new int[]{}),
    KERIS_PARTISAN_OF_THE_SUN("Keris partisan of the sun", "Melee", new int[]{}),
    LEAF_BLADED_BATTLEAXE("Leaf-bladed battleaxe", "Melee", new int[]{ItemID.LEAFBLADED_BATTLEAXE}),
    LEAF_BLADED_SPEAR("Leaf-bladed spear", "Melee", new int[]{}),
    LEAF_BLADED_SWORD("Leaf-bladed sword", "Melee", new int[]{ItemID.LEAFBLADED_SWORD}),
    LUCKY_CUTLASS("Lucky cutlass", "Melee", new int[]{}),
    MITHRIL_2H_SWORD("Mithril 2h sword", "Melee", new int[]{ItemID.MITHRIL_2H_SWORD}),
    MITHRIL_BATTLEAXE("Mithril battleaxe", "Melee", new int[]{ItemID.MITHRIL_BATTLEAXE}),
    MITHRIL_CLAWS("Mithril claws", "Melee", new int[]{}),
    MITHRIL_DAGGER("Mithril dagger", "Melee", new int[]{ItemID.MITHRIL_DAGGER}),
    MITHRIL_HALBERD("Mithril halberd", "Melee", new int[]{}),
    MITHRIL_HASTA("Mithril hasta", "Melee", new int[]{}),
    MITHRIL_LONGSWORD("Mithril longsword", "Melee", new int[]{ItemID.MITHRIL_LONGSWORD}),
    MITHRIL_MACE("Mithril mace", "Melee", new int[]{ItemID.MITHRIL_MACE}),
    MITHRIL_SCIMITAR("Mithril scimitar", "Melee", new int[]{ItemID.MITHRIL_SCIMITAR}),
    MITHRIL_SPEAR("Mithril spear", "Melee", new int[]{}),
    MITHRIL_SWORD("Mithril sword", "Melee", new int[]{ItemID.MITHRIL_SWORD}),
    MITHRIL_WARHAMMER("Mithril warhammer", "Melee", new int[]{}),
    NOXIOUS_HALBERD("Noxious halberd", "Melee", new int[]{ItemID.NOXIOUS_HALBERD}),
    OSMUMTENS_FANG("Osmumten's fang", "Melee", new int[]{ItemID.OSMUMTENS_FANG}),
    OSMUMTENS_FANG_OR("Osmumten's fang (or)", "Melee", new int[]{ItemID.OSMUMTENS_FANG_ORNAMENT}),
    ROLLING_PIN("Rolling pin", "Melee", new int[]{}),
    RUNE_2H_SWORD("Rune 2h sword", "Melee", new int[]{ItemID.RUNE_2H_SWORD}),
    RUNE_BATTLEAXE("Rune battleaxe", "Melee", new int[]{ItemID.RUNE_BATTLEAXE}),
    RUNE_CLAWS("Rune claws", "Melee", new int[]{}),
    RUNE_DAGGER("Rune dagger", "Melee", new int[]{ItemID.RUNE_DAGGER}),
    RUNE_HALBERD("Rune halberd", "Melee", new int[]{}),
    RUNE_HASTA("Rune hasta", "Melee", new int[]{}),
    RUNE_LONGSWORD("Rune longsword", "Melee", new int[]{ItemID.RUNE_LONGSWORD}),
    RUNE_MACE("Rune mace", "Melee", new int[]{ItemID.RUNE_MACE}),
    RUNE_SCIMITAR("Rune scimitar", "Melee", new int[]{ItemID.RUNE_SCIMITAR}),
    RUNE_SCIMITAR_BR("Rune scimitar BR", "Melee", new int[]{ItemID.BR_RUNE_SCIMITAR}),
    RUNE_SCIMITAR_GUTHIX("Rune scimitar (guthix)", "Melee", new int[]{ItemID.RUNE_SCIMITAR_GUTHIX}),
    RUNE_SCIMITAR_SARADOMIN("Rune scimitar (saradomin)", "Melee", new int[]{ItemID.RUNE_SCIMITAR_SARADOMIN}),
    RUNE_SCIMITAR_ZAMORAK("Rune scimitar (zamorak)", "Melee", new int[]{ItemID.RUNE_SCIMITAR_ZAMORAK}),
    RUNE_SPEAR("Rune spear", "Melee", new int[]{}),
    RUNE_SWORD("Rune sword", "Melee", new int[]{ItemID.RUNE_SWORD}),
    RUNE_WARHAMMER("Rune warhammer", "Melee", new int[]{}),
    SANGUINE_SCYTHE_OF_VITUR("Sanguine scythe of vitur", "Melee", new int[]{}),
    SARACHNIS_CUDGEL("Sarachnis cudgel", "Melee", new int[]{}),
    SARADOMIN_GODSWORD("Saradomin godsword", "Melee", new int[]{}),
    SARADOMIN_GODSWORD_OR("Saradomin godsword (or)", "Melee", new int[]{}),
    SARADOMIN_MJOLNIR("Saradomin mjolnir", "Melee", new int[]{}),
    SARADOMIN_SWORD("Saradomin sword", "Melee", new int[]{ItemID.SARADOMIN_SWORD}),
    SARADOMINS_BLESSED_SWORD("Saradomin's blessed sword", "Melee", new int[]{}),
    SCYTHE_OF_VITUR("Scythe of vitur", "Melee", new int[]{ItemID.SCYTHE_OF_VITUR}),
    SCYTHE_OF_VITUR_2("Scythe of vitur 2", "Melee", new int[]{ItemID.ROTTEN_SCYTHE}),
    SCYTHE_OF_VITUR_OR("Scythe of vitur OR", "Melee", new int[]{ItemID.SCYTHE_OF_VITUR_OR}),
    SCYTHE_OF_VITUR_SANGUINE("Scythe of vitur Sanguine", "Melee", new int[]{ItemID.SCYTHE_OF_VITUR_BL}),
    SCYTHE_OF_VITUR_CORRUPTED("Scythe of vitur corrupted", "Melee", new int[]{ItemID.DEADMAN_BLIGHTED_SCYTHE_OF_VITUR}),
    SILVER_SICKLE("Silver sickle", "Melee", new int[]{}),
    SILVER_SICKLE_B("Silver sickle (b)", "Melee", new int[]{}),
    SILVERLIGHT("Silverlight", "Melee", new int[]{}),
    SOULREAPER_AXE("Soulreaper axe", "Melee", new int[]{ItemID.SOULREAPER}),
    SOULREAPER_AXE_B("Soulreaper axe B", "Melee", new int[]{ItemID.BETA_ITEM_1}),
    SPEAR_LAST_MAN_STANDING("Spear (Last Man Standing)", "Melee", new int[]{}),
    STATIUSS_WARHAMMER("Statius's warhammer", "Melee", new int[]{ItemID.STATIUS_WARHAMMER}),
    STATIUSS_WARHAMMER_BH("Statius's warhammer (bh)", "Melee", new int[]{ItemID.STATIUS_WARHAMMER_BH}),
    STATIUSS_WARHAMMER_DEADMAN_MODE("Statius's warhammer (Deadman Mode)", "Melee", new int[]{ItemID.BR_STATIUS_WARHAMMER}),
    STEEL_2H_SWORD("Steel 2h sword", "Melee", new int[]{ItemID.STEEL_2H_SWORD}),
    STEEL_BATTLEAXE("Steel battleaxe", "Melee", new int[]{}),
    STEEL_CLAWS("Steel claws", "Melee", new int[]{}),
    STEEL_DAGGER("Steel dagger", "Melee", new int[]{}),
    STEEL_HALBERD("Steel halberd", "Melee", new int[]{}),
    STEEL_HASTA("Steel hasta", "Melee", new int[]{}),
    STEEL_LONGSWORD("Steel longsword", "Melee", new int[]{ItemID.STEEL_LONGSWORD}),
    STEEL_MACE("Steel mace", "Melee", new int[]{}),
    STEEL_SCIMITAR("Steel scimitar", "Melee", new int[]{}),
    STEEL_SPEAR("Steel spear", "Melee", new int[]{}),
    STEEL_SWORD("Steel sword", "Melee", new int[]{ItemID.STEEL_SWORD}),
    STEEL_WARHAMMER("Steel warhammer", "Melee", new int[]{}),
    SULPHUR_BLADES("Sulphur blades", "Melee", new int[]{}),
    SWIFT_BLADE("Swift blade", "Melee", new int[]{}),
    TOKTZ_XIL_AK("Toktz-xil-ak", "Melee", new int[]{ItemID.TZHAAR_SPLITSWORD}),
    TOKTZ_XIL_EK("Toktz-xil-ek", "Melee", new int[]{}),
    TORAGS_HAMMERS("Torag's hammers", "Melee", new int[]{}),
    TRAINING_SWORD("Training sword", "Melee", new int[]{}),
    TWO_HANDED_SWORD("Two-handed sword", "Melee", new int[]{}),
    TZHAAR_KET_EM("Tzhaar-ket-em", "Melee", new int[]{}),
    TZHAAR_KET_OM("Tzhaar-ket-om", "Melee", new int[]{}),
    TZHAAR_KET_OM_T("Tzhaar-ket-om (t)", "Melee", new int[]{}),
    URSINE_CHAINMACE("Ursine chainmace", "Melee", new int[]{}),
    VERACS_FLAIL("Verac's flail", "Melee", new int[]{}),
    VESTAS_BLIGHTED_LONGSWORD("Vesta's blighted longsword", "Melee", new int[]{}),
    VESTAS_LONGSWORD_BH("Vesta's longsword (bh)", "Melee", new int[]{}),
    VESTAS_LONGSWORD_DEADMAN_MODE("Vesta's longsword (Deadman Mode)", "Melee", new int[]{}),
    VESTAS_SPEAR_BH("Vesta's spear (bh)", "Melee", new int[]{}),
    VESTAS_SPEAR_DEADMAN_MODE("Vesta's spear (Deadman Mode)", "Melee", new int[]{}),
    VIGGORAS_CHAINMACE("Viggora's chainmace", "Melee", new int[]{}),
    VOID_KNIGHT_MACE("Void knight mace", "Melee", new int[]{}),
    VOIDWAKER("Voidwaker", "Melee", new int[]{ItemID.VOIDWAKER}),
    VOIDWAKER_BR("Voidwaker BR", "Melee", new int[]{ItemID.BR_VOIDWAKER}),
    VOIDWAKER_DM("Voidwaker DM", "Melee", new int[]{ItemID.DEADMAN_VOIDWAKER}),
    CORRUPTED_VOIDWAKER_BR("Corrupted voidwaker BR", "Melee", new int[]{ItemID.DEADMAN_BLIGHTED_VOIDWAKER}),
    VOLCANIC_ABYSSAL_WHIP("Volcanic abyssal whip", "Melee", new int[]{}),
    WHITE_2H_SWORD("White 2h sword", "Melee", new int[]{}),
    WHITE_BATTLEAXE("White battleaxe", "Melee", new int[]{}),
    WHITE_CLAWS("White claws", "Melee", new int[]{}),
    WHITE_DAGGER("White dagger", "Melee", new int[]{}),
    WHITE_HALBERD("White halberd", "Melee", new int[]{}),
    WHITE_LONGSWORD("White longsword", "Melee", new int[]{}),
    WHITE_MACE("White mace", "Melee", new int[]{}),
    WHITE_SCIMITAR("White scimitar", "Melee", new int[]{}),
    WHITE_SWORD("White sword", "Melee", new int[]{}),
    WHITE_WARHAMMER("White warhammer", "Melee", new int[]{}),
    ZAMORAK_GODSWORD("Zamorak godsword", "Melee", new int[]{}),
    ZAMORAK_GODSWORD_OR("Zamorak godsword (or)", "Melee", new int[]{}),
    ZAMORAK_MJOLNIR("Zamorak mjolnir", "Melee", new int[]{}),
    ZAMORAKIAN_HASTA("Zamorakian hasta", "Melee", new int[]{ItemID.ZAMORAK_HASTA}),
    ZAMORAKIAN_SPEAR("Zamorakian spear", "Melee", new int[]{ItemID.ZAMORAK_SPEAR}),
    ZOMBIE_AXE("Zombie axe", "Melee", new int[]{}),
    LIGHTBEARER_BR("Lightbearer BR", "Melee", new int[]{ItemID.BR_LIGHTBEARER});

    private final String itemName;
    private final String attackType;
    private final int[] objectIds;

    WeaponID(String itemName, String attackType, int[] objectIds) {
        this.itemName = itemName;
        this.attackType = attackType;
        this.objectIds = objectIds;
    }

    public static WeaponID getByObjectId(int objectId) {
        return Arrays.stream(values())
                .filter(w -> Arrays.stream(w.getObjectIds()).anyMatch(id -> id == objectId))
                .findFirst()
                .orElse(null);
    }
}
